### ISSUE TITLE
Add support for `ILayoutElement` properties

### ISSUE THREAD

**Issue by RichardWepnerPD** [gilzoide/unity-flex-ui#26]
The `ILayoutElement` defines some properties that are used by other components in UGUI and thus vital for defining UIs using UGUI. These are min, preferred, and flexible width and height.

One example use case would be a `ScrollRect` containing content layed out using the `FlexLayout`. Since the content element of the scroll rect needs to have a size in order for the scorlling to be limited accordingly, a `ContentSizeFitter` is frequently used to restrict the size of the element to the preferred height (or width).

Adressing this might also resolve the issue https://github.com/gilzoide/unity-flex-ui/issues/24.

**Comment by gilzoide** [comment]
I'm closing this issue and focusing this discussion in #27, which addresses this topic and more.
